// <auto-generated />
namespace GreenGrassWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_request_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_request_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201801141357168_change_request_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
